const CURSO = [
  {
    num:"01", titulo:"Fundamentos de Hardware", objetivo:"Apresentar os conceitos básicos de hardware, software e a evolução dos computadores.",
    aulas:[
      {t:"Introdução e evolução dos computadores", tipo:"teoria",
       obj:"Compreender a trajetória do computador e identificar os marcos históricos principais.",
       conteudo:["Gerações de computadores (válvulas, transistores, circuitos integrados, microprocessadores)","Principais fabricantes e padrões de mercado","Do mainframe ao computador pessoal"],
       pratica:"Linha do tempo com os 8 principais marcos da evolução do computador."},
      {t:"Hardware, software e organização do computador", tipo:"teoria",
       obj:"Distinguir hardware de software e entender as partes fundamentais de um computador.",
       conteudo:["Conceitos de hardware e software","Unidade central de processamento (CPU)","Memória, armazenamento e dispositivos de entrada/saída"],
       pratica:"Identificação de componentes a partir de imagens de uma placa-mãe real."},
      {t:"Arquitetura e funcionamento do computador", tipo:"teoria",
       obj:"Explicar a arquitetura de Von Neumann e o ciclo de processamento.",
       conteudo:["Arquitetura de Von Neumann","Ciclo buscar–decodificar–executar","Barramento, clock e paralelismo"],
       pratica:"Simulação do ciclo de instrução usando um fluxograma."},
      {t:"Sistemas de numeração e unidades de medida", tipo:"mista",
       obj:"Converter números entre bases e dominar unidades de medida de dados.",
       conteudo:["Binário, octal, decimal e hexadecimal","Conversões entre bases","Bits, bytes e múltiplos (KB, MB, GB, TB)"],
       pratica:"Exercícios de conversão binário→decimal e decimal→hexadecimal."},
      {t:"Segurança no trabalho, ESD e organização da bancada", tipo:"pratica",
       obj:"Aplicar normas de segurança e práticas de proteção contra descarga eletrostática.",
       conteudo:["Descarga eletrostática (ESD) e como evitá-la","Equipamentos de proteção e boas práticas","Organização da bancada e ferramentas essenciais"],
       pratica:"Montagem de bancada com pulseira antiestática e organização das ferramentas."}
    ]
  },
  {
    num:"02", titulo:"Componentes Internos do Computador", objetivo:"Conhecer em detalhe cada componente interno e entender suas funções e compatibilidade.",
    aulas:[
      {t:"Gabinete e fonte de alimentação", tipo:"mista",
       obj:"Identificar tipos de gabinetes e calcular a fonte adequada.",
       conteudo:["Form factors de gabinete (ATX, Micro-ATX, Mini-ITX)","Fonte ATX: potência, eficiência (80 Plus) e conectores","Cálculo de consumo de energia"],
       pratica:"Cálculo de potência da fonte para uma configuração exemplo."},
      {t:"Placa-mãe: form factors, chipsets e sockets", tipo:"teoria",
       obj:"Interpretar a placa-mãe e escolher modelos compatíveis.",
       conteudo:["Form factors e padrões de montagem","Chipset, slots e conectores","Sockets Intel e AMD"],
       pratica:"Identificação de conectores e slots em uma placa-mãe."},
      {t:"Processador (CPU): arquitetura e refrigeração", tipo:"mista",
       obj:"Compreender o funcionamento da CPU e seu sistema de refrigeração.",
       conteudo:["Núcleos, threads, clock e cache","Arquiteturas Intel e AMD","Coolers, pasta térmica e AIO"],
       pratica:"Aplicação correta de pasta térmica e instalação de cooler."},
      {t:"Memória RAM", tipo:"mista",
       obj:"Escolher e instalar módulos de memória compatíveis.",
       conteudo:["DDR4 e DDR5: velocidade, latência e tensão","Canais duplos e configuração de slots","Erros comuns e cuidados na instalação"],
       pratica:"Instalação de pentes de memória em dual channel."},
      {t:"Armazenamento: HD, SSD SATA e NVMe", tipo:"mista",
       obj:"Diferenciar tecnologias de armazenamento e instalá-las.",
       conteudo:["HD mecânico e SSD","Interfaces SATA e NVMe (M.2)","Capacidade, cache e durabilidade"],
       pratica:"Instalação de SSD SATA e NVMe M.2."},
      {t:"Placa de vídeo (GPU) e vídeo integrado", tipo:"teoria",
       obj:"Entender o papel da GPU e a diferença entre vídeo dedicado e integrado.",
       conteudo:["GPU dedicada e integrada","VRAM, conexões e saídas de vídeo","Fonte de alimentação e GPU"],
       pratica:"Identificação de modelos de GPU e seus requisitos de fonte."},
      {t:"Compatibilidade e escolha de componentes", tipo:"mista",
       obj:"Montar uma configuração compatível dentro de um orçamento.",
       conteudo:["Cruzamento de compatibilidade (socket, RAM, fonte)","Balanceamento de desempenho e custo","Montagem de orçamentos"],
       pratica:"Elaboração de 3 orçamentos completos de configuração."}
    ]
  },
  {
    num:"03", titulo:"Montagem de Computadores", objetivo:"Montar um computador completo, do zero, de forma segura e organizada.",
    aulas:[
      {t:"Ferramentas, bancada e checklist de montagem", tipo:"teoria",
       obj:"Preparar ferramentas e checklist antes de iniciar a montagem.",
       conteudo:["Ferramentas necessárias (chaves, alicates, espátula)","Checklist de componentes","Ordem lógica de montagem"],
       pratica:"Elaboração de um checklist personalizado de montagem."},
      {t:"Instalação da fonte de alimentação", tipo:"pratica",
       obj:"Fixar a fonte e organizar os cabos de energia.",
       conteudo:["Posicionamento e fixação da fonte","Conectores 24 pinos, 8 pinos CPU, SATA e PCIe","Gerenciamento básico de cabos"],
       pratica:"Instalação real da fonte em um gabinete."},
      {t:"Instalação da placa-mãe, CPU e cooler", tipo:"pratica",
       obj:"Instalar placa-mãe, processador e sistema de refrigeração corretamente.",
       conteudo:["Instalação do backplate e da placa-mãe","Posicionamento do processador no socket","Fixação do cooler e conexão do fan"],
       pratica:"Montagem guiada de placa-mãe, CPU e cooler."},
      {t:"Instalação de RAM, armazenamento e GPU", tipo:"pratica",
       obj:"Instalar memórias, dispositivos de armazenamento e placa de vídeo.",
       conteudo:["Slots de RAM e pinos de alinhamento","Fixação de HD/SSD no gabinete","Encaixe da placa de vídeo no slot PCIe"],
       pratica:"Finalização da instalação dos componentes principais."},
      {t:"Cabeamento e gerenciamento interno", tipo:"pratica",
       obj:"Organizar os cabos para garantir fluxo de ar e estética.",
       conteudo:["Roteamento de cabos no gabinete","Uso de abraçadeiras e passa-cabos","Fluxo de ar e posição das ventoinhas"],
       pratica:"Reorganização completa do cabeamento interno."},
      {t:"Primeira inicialização: POST, BIOS e UEFI", tipo:"pratica",
       obj:"Ligar o computador pela primeira vez e configurar a BIOS/UEFI.",
       conteudo:["Teste POST e sinais sonoros","Acesso e configuração da UEFI","Detecção de componentes e boot"],
       pratica:"Primeiro boot: validação de todos os componentes na BIOS."}
    ]
  },
  {
    num:"04", titulo:"Instalação de Sistemas Operacionais", objetivo:"Instalar e configurar sistemas operacionais com preparo profissional.",
    aulas:[
      {t:"Preparação de mídias de instalação", tipo:"pratica",
       obj:"Criar pendrives bootáveis e entender o processo de boot.",
       conteudo:["Ferramentas (Rufus, Ventoy, balenaEtcher)","Criação de mídia de instalação","Menu de boot e prioridade"],
       pratica:"Criação de um pendrive bootável para Windows e para Linux."},
      {t:"Instalação do Windows", tipo:"pratica",
       obj:"Instalar o Windows do zero e realizar configurações iniciais.",
       conteudo:["Particionamento de disco","Fluxo de instalação","Configurações de conta e privacidade"],
       pratica:"Instalação completa do Windows em máquina de teste."},
      {t:"Instalação de drivers e atualizações", tipo:"mista",
       obj:"Instalar e atualizar drivers de forma correta.",
       conteudo:["Windows Update e drivers de chipset/GPU","Gerenciador de dispositivos","Solução de drivers com problema"],
       pratica:"Instalação e verificação de drivers após o sistema."},
      {t:"Instalação do Linux", tipo:"pratica",
       obj:"Instalar uma distribuição Linux e conhecer o ecossistema.",
       conteudo:["Distribuições populares (Ubuntu, Mint)","Particionamento e dual boot","Instalação de aplicativos e drivers"],
       pratica:"Instalação do Linux com dual boot em máquina de teste."}
    ]
  },
  {
    num:"05", titulo:"Manutenção Preventiva", objetivo:"Aplicar rotinas de manutenção que evitem falhas e prolonguem a vida útil do equipamento.",
    aulas:[
      {t:"Plano de manutenção preventiva", tipo:"mista",
       obj:"Estruturar um cronograma de manutenção para computadores.",
       conteudo:["Frequência ideal por tipo de uso","Checklist de inspeção","Registro de manutenções realizadas"],
       pratica:"Criação de um plano de manutenção trimestral."},
      {t:"Limpeza e conservação de componentes", tipo:"pratica",
       obj:"Limpar computadores com segurança e eficiência.",
       conteudo:["Limpeza interna e externa","Ar comprimido, escovas e produtos","Cuidados com conectores e ventoinhas"],
       pratica:"Limpeza completa de um computador de mesa."},
      {t:"Backup e restauração de dados", tipo:"mista",
       obj:"Implementar estratégias de backup e recuperação de dados.",
       conteudo:["Regra 3-2-1 de backup","Backup em nuvem e local","Criação de imagens de sistema"],
       pratica:"Configuração de backup automático e teste de restauração."},
      {t:"Monitoramento da saúde do hardware", tipo:"pratica",
       obj:"Monitorar temperaturas, discos e memória do sistema.",
       conteudo:["Temperaturas e tensões (HWMonitor)","Status de saúde do SSD/HD (SMART)","Teste de desempenho e estresse"],
       pratica:"Diagnóstico de saúde completa de uma máquina."},
      {t:"Atualização de BIOS e firmware", tipo:"mista",
       obj:"Atualizar BIOS e firmware de forma segura.",
       conteudo:["Quando atualizar a BIOS","Procedimento seguro de atualização","Recuperação após falha de BIOS"],
       pratica:"Simulação do processo de atualização da BIOS."}
    ]
  },
  {
    num:"06", titulo:"Diagnóstico e Manutenção Corretiva", objetivo:"Desenvolver método para diagnosticar e corrigir falhas comuns de hardware.",
    aulas:[
      {t:"Metodologia de diagnóstico de falhas", tipo:"mista",
       obj:"Aplicar um método lógico para identificar falhas.",
       conteudo:["Coleta de informações e sintomas","Isolamento por componentes","Teste da hipótese e validação"],
       pratica:"Resolução de estudos de caso de falhas."},
      {t:"Falhas de alimentação elétrica", tipo:"mista",
       obj:"Identificar e corrigir falhas relacionadas à fonte e energia.",
       conteudo:["Sintomas de fonte defeituosa","Medição de tensões","Estabilizadores, no-break e proteção"],
       pratica:"Teste de fonte com multímetro e teste de 24 pinos."},
      {t:"Falhas de memória e armazenamento", tipo:"mista",
       obj:"Diagnosticar problemas em RAM e discos.",
       conteudo:["Tela azul e erros de memória","Testes com MemTest86","Falhas de disco e setores defeituosos"],
       pratica:"Execução de testes de memória e de integridade do disco."},
      {t:"Falhas de vídeo e placa-mãe", tipo:"mista",
       obj:"Diagnosticar problemas de vídeo e na placa-mãe.",
       conteudo:["Sem imagem: causas e soluções","Testes com outra GPU/rampa","Capacitores e sinais da placa-mãe"],
       pratica:"Diagnóstico de máquina sem sinal de vídeo."},
      {t:"Superaquecimento e problemas de refrigeração", tipo:"pratica",
       obj:"Resolver problemas de temperatura excessiva.",
       conteudo:["Sintomas de superaquecimento","Substituição de pasta térmica","Reforço de refrigeração do gabinete"],
       pratica:"Troca de pasta térmica e otimização do fluxo de ar."},
      {t:"Ferramentas de diagnóstico e testes avançados", tipo:"pratica",
       obj:"Usar ferramentas profissionais de diagnóstico.",
       conteudo:["Post tester e placas de diagnóstico","Ferramentas de software (AIDA64, CrystalDisk)","Emissão de laudo técnico"],
       pratica:"Emissão de um laudo técnico completo de uma máquina."}
    ]
  },
  {
    num:"07", titulo:"Redes e Conectividade", objetivo:"Montar, configurar e manter redes domésticas e de pequenas empresas.",
    aulas:[
      {t:"Fundamentos de redes", tipo:"teoria",
       obj:"Entender conceitos básicos de redes de computadores.",
       conteudo:["Modelo OSI e TCP/IP","IP, máscara, gateway e DNS","Equipamentos de rede (switch, roteador, access point)"],
       pratica:"Mapeamento de uma rede residencial com identificação de IPs."},
      {t:"Cabeamento estruturado e crimpagem", tipo:"pratica",
       obj:"Confeccionar cabos de rede e certificar conexões.",
       conteudo:["Cabo UTP e categorias (Cat5e, Cat6)","Padrões T568A/T568B","Crimpagem e testador de cabos"],
       pratica:"Crimpagem de cabos e teste com certificador de rede."},
      {t:"Wi-Fi e roteadores", tipo:"mista",
       obj:"Configurar redes sem fio e roteadores.",
       conteudo:["Padrões Wi-Fi (2.4GHz e 5GHz)","Configuração de roteador","Segurança e senhas"],
       pratica:"Configuração completa de um roteador residencial."},
      {t:"Configuração de rede no sistema operacional", tipo:"pratica",
       obj:"Configurar rede no Windows e Linux.",
       conteudo:["IP estático e dinâmico (DHCP)","Compartilhamento de arquivos","Diagnóstico de conectividade (ping, tracert)"],
       pratica:"Configuração de rede fixa e teste de conectividade."},
      {t:"Internet, protocolos e segurança básica", tipo:"teoria",
       obj:"Compreender como a internet funciona e proteger a rede.",
       conteudo:["HTTP/HTTPS, DNS e DHCP","Firewall e proteção do roteador","Básico de segurança de rede"],
       pratica:"Análise de segurança de uma rede doméstica."}
    ]
  },
  {
    num:"08", titulo:"Atendimento, Ordem de Serviço e Mercado", objetivo:"Preparar o profissional para trabalhar com atendimento técnico e gestão de oficina.",
    aulas:[
      {t:"Ordem de serviço e orçamento", tipo:"mista",
       obj:"Elaborar ordens de serviço e orçamentos profissionais.",
       conteudo:["Estrutura de uma ordem de serviço","Cálculo de mão de obra e peças","Prazos e garantias"],
       pratica:"Criação de uma ordem de serviço completa para um atendimento real."},
      {t:"Gestão de peças e estoque", tipo:"mista",
       obj:"Gerir peças, estoque e fornecedores da oficina.",
       conteudo:["Controle de estoque de peças","Escolha de fornecedores e garantias","Comissão e margem de lucro"],
       pratica:"Montagem de planilha de controle de estoque e preços."},
      {t:"Ética e atendimento ao cliente", tipo:"teoria",
       obj:"Aplicar boas práticas de atendimento e comunicação.",
       conteudo:["Comunicação clara e técnica","Gerenciamento de expectativas","Postura profissional e sigilo"],
       pratica:"Simulação de atendimento com cliente insatisfeito."},
      {t:"Segurança da informação e LGPD", tipo:"teoria",
       obj:"Aplicar princípios de segurança de dados no atendimento.",
       conteudo:["Proteção de dados do cliente","LGPD e boas práticas","Descarte seguro de equipamentos"],
       pratica:"Elaboração de termo de consentimento e manuseio de dados."},
      {t:"Tendências, certificações e carreira", tipo:"teoria",
       obj:"Planejar a carreira e identificar oportunidades do mercado.",
       conteudo:["Certificações (CompTIA A+, etc.)","Mercado de trabalho e empreendedorismo","Tendências: PC, notebook, servidores"],
       pratica:"Elaboração de um plano de carreira individual."}
    ]
  }
];
